services:

  backend_stock_qdov:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend_stock_qdov:latest
    container_name: backend_stock_qdov
    restart: unless-stopped
    ports:
      - "49165:9000"
    env_file:
      - .env.production
    volumes:
      - app_bootstrap_cache:/var/www/bootstrap/cache
      - storage_volume:/var/www/storage
      - vendor_volume:/var/www/public/vendor
    networks:
      - elk


  nginx:
    image: nginx:stable-alpine
    container_name: backend_stock_qdov_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - storage_volume:/var/www/storage
      - vendor_volume:/var/www/public/vendor
    depends_on:
      - backend_stock_qdov
    networks:
      - elk

  db:
    image: mysql:8.0
    container_name: stock_qdov_bd
    restart: always
    environment:
      MYSQL_DATABASE: stock_qdov_bd
      MYSQL_ROOT_PASSWORD: monMotDePasseSecurise
      MYSQL_ROOT_HOST: '%'
    ports:
      - "49170:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - elk

volumes:
  elasticsearch-data:
    driver: local

  dbdata:
    driver: local

  app_bootstrap_cache:
  storage_volume:
  vendor_volume:

networks:
  elk:
    driver: bridge

